"""create financial records table

Revision ID: ab1277260608
Revises: 3472195c673b
Create Date: 2026-10-03 21:01:36.204879

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ab1277260608'
down_revision: Union[str, Sequence[str], None] = '3472195c673b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('financial_records',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('startup_id', sa.Uuid(), nullable=False),
    sa.Column('fiscal_year', sa.Integer(), nullable=False),
    sa.Column('revenue', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('gross_profit', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('operating_expenses', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('ebitda', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('net_income', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('cash_balance', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('total_debt', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['startup_id'], ['startups.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('startup_id', 'fiscal_year', name='uq_financial_records_startup_year')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('financial_records')
    # ### end Alembic commands ###
